---
- name: add universe
  ansible.builtin.command: apt-add-repository -y universe
  
- name: "install packages"
  apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 3600

- name: "install packages"
  apt:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ packages }}"
