---
- name: "install packages"
  community.general.pacman:
    update_cache: yes
    update: yes

- name: "install packages"
  community.general.pacman:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ packages }}"
